# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

# Could not dump table "albums" because of following StandardError
#   Unknown type 'enum' for column 'status'

  create_table "artists", :force => true do |t|
    t.column "name",       :string
    t.column "sort_name",  :string
    t.column "note",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "artists", ["name"], :name => "index_artists_on_name"

  create_table "comments", :force => true do |t|
    t.column "body",             :text
    t.column "commentable_id",   :integer
    t.column "commentable_type", :string
    t.column "user_id",          :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "formats", :force => true do |t|
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "formats", ["name"], :name => "index_formats_on_name"

  create_table "genres", :force => true do |t|
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "genres", ["name"], :name => "index_genres_on_name"

  create_table "labels", :force => true do |t|
    t.column "name",         :string
    t.column "contact_name", :string
    t.column "email",        :string
    t.column "address",      :string
    t.column "city",         :string
    t.column "state",        :string
    t.column "zip",          :integer
    t.column "country",      :string
    t.column "fax",          :string
    t.column "phone",        :string
    t.column "note",         :text
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  add_index "labels", ["name"], :name => "index_labels_on_name"

  create_table "promoters", :force => true do |t|
    t.column "name",         :string
    t.column "contact_name", :string
    t.column "email",        :string
    t.column "phone",        :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  add_index "promoters", ["name"], :name => "index_promoters_on_name"

  create_table "reviews", :force => true do |t|
    t.column "body",       :text
    t.column "user_id",    :integer
    t.column "album_id",   :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "reviews", ["user_id", "album_id"], :name => "index_reviews_on_user_id_and_album_id"
  add_index "reviews", ["album_id"], :name => "index_reviews_on_album_id", :unique => true
  add_index "reviews", ["user_id"], :name => "index_reviews_on_user_id"

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"
  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

# Could not dump table "users" because of following StandardError
#   Unknown type 'enum' for column 'affiliation'

end
