# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "formats", :force => true do |t|
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "genres", :force => true do |t|
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "labels", :force => true do |t|
    t.column "name",         :string
    t.column "contact_name", :string
    t.column "email",        :string
    t.column "address",      :string
    t.column "city",         :string
    t.column "state",        :string
    t.column "zip",          :integer
    t.column "country",      :string
    t.column "fax",          :string
    t.column "phone",        :string
    t.column "note",         :text
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "promoters", :force => true do |t|
    t.column "name",         :string
    t.column "contact_name", :string
    t.column "email",        :string
    t.column "phone",        :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "first_name",                :string
    t.column "last_name",                 :string
    t.column "phone",                     :string
    t.column "affiliation",               :enum,     :limit => [:undergraduate, :graduate, :alumni, :community, :faculty, :staff]
    t.column "status",                    :enum,     :limit => [:active, :inactive, :banned]
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
  end

end
