# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

# Could not dump table "users" because of following StandardError
#   Unknown type 'enum' for column 'affiliation'

end
